"""adicionando codigo do cliente

Revision ID: 576eb2ec98a0
Revises: b7bb4bc229a8
Create Date: 2020-07-24 20:49:33.666230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576eb2ec98a0'
down_revision = 'b7bb4bc229a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('codigo_cliente', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'codigo_cliente')
    # ### end Alembic commands ###
